name: 测试学习发布打包软件

on:
  push:
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
          - goarch: amd64
            goos: darwin
          - goarch: arm64
            goos: linux
          - goarch: arm64
            goos: darwin
          - goarch: amd64
            goos: windows
    steps:
    - uses: actions/checkout@master
    - name: 打包当前文件
      run: |
        uname -a
        pip install pyinstaller
        pyinstaller -F *.py
        tar -zcvf ${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz dist
        
    - name: 发布打包程序
      uses: softprops/action-gh-release@v1
      with:
          tag_name: V1.${{ github.run_id }} #V0.1 # 你也可以将其输入为V1.2……
          name: V1.${{ github.run_id }} #V0.1 # 你也可以将其输入为V1.2……
          body: 测试自动发布版本号
          draft: false  # 是否是草稿
          prerelease: true # 是否是预览版
          files: |
              *.tar.gz
