name: 测试学习发布打包软件

on:
  push:
jobs:
  build:
   # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
          - goarch: amd64
            goos: darwin
          - goarch: arm64
            goos: linux
          - goarch: arm64
            goos: darwin
    steps:
    - uses: actions/checkout@master
    - name: 打包当前文件
      run: |
        pip install pyinstaller
        pyinstaller -F *.py
        
    - name: 发布打包程序
      uses: softprops/action-gh-release@v1
      with:
          tag_name: V0.${{ github.run_id }}.dev #V0.1 # 你也可以将其输入为V1.2……
          name: V0.${{ github.run_id }}.dev #V0.1 # 你也可以将其输入为V1.2……
          body: 测试自动发布版本号
          draft: false  # 是否是草稿
          prerelease: true # 是否是预览版
          files: |
            # 你要上传的文件
              dist/*
