name: 测试学习发布打包软件

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: 打包当前文件
      run: |
        pip install pyinstaller
        pyinstaller -F *.py
        
    - name: 发布打包程序
        uses: softprops/action-gh-release@v1
        with:
            tag_name: V0.${{ github.run_id }} # 你也可以将其输入为V1.2……
            name: V0.${{ github.run_id }} # 你也可以将其输入为V1.2……
            body: TODO New Release.
            draft: false  # 是否是草稿
            prerelease: true # 是否是预览版
            files: |
                dist/*
